# Generated by Django 4.1.3 on 2023-03-16 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembleias',
            fields=[
                ('assembleia_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID.Assembleia')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('orgao', models.CharField(max_length=20, verbose_name='Orgão')),
                ('cpostal', models.CharField(max_length=10, verbose_name='Cod.Postal')),
                ('localidade', models.CharField(max_length=80, verbose_name='Localidade')),
                ('dt_assembleia', models.DateField(verbose_name='Dt.Assembleia')),
                ('convocados', models.IntegerField(default=0, verbose_name='Convocados')),
                ('presencas', models.IntegerField(default=0, verbose_name='Presenças')),
                ('rep_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Representação Total')),
                ('rep_assembl', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Representação Assembleia')),
            ],
        ),
        migrations.CreateModel(
            name='CodPostais',
            fields=[
                ('codpostal', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cod.Postal')),
                ('localidade', models.CharField(max_length=50, verbose_name='Localidade')),
            ],
        ),
        migrations.CreateModel(
            name='TiposDespesas',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id.Tipo')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('socio_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Socio')),
                ('nsocio', models.IntegerField(default=0, verbose_name='NºSócio')),
                ('nome', models.CharField(max_length=80)),
                ('morada', models.CharField(max_length=80)),
                ('localidade', models.CharField(max_length=80, verbose_name='Localidade')),
                ('cpostlocal', models.CharField(max_length=80, verbose_name='Local.Cod.Post')),
                ('telemovel', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('lotes', models.CharField(max_length=80, verbose_name='Lotes')),
                ('compdivida', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Comp. Devidas')),
                ('anuidivida', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Anuid. Devidas')),
                ('dt_admissao', models.DateField(verbose_name='Dt.Admissão')),
                ('estado', models.CharField(max_length=15)),
                ('cpostal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Codpost', to='gestaugi.codpostais', verbose_name='Cod.Postal')),
            ],
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('lote_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Lote')),
                ('nlote', models.IntegerField(default=0, verbose_name='NºLote')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('local', models.CharField(max_length=80)),
                ('dt_aquisicao', models.DateField(verbose_name='Dt.Aquisição')),
                ('dt_venda', models.DateField(blank=True, null=True, verbose_name='Dt.Venda')),
                ('nfogos', models.IntegerField(default=0, verbose_name='NºFogos')),
                ('frenteslote', models.IntegerField(default=0, verbose_name='Frentes Lote')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Socios', to='gestaugi.socios', verbose_name='NºSocio')),
            ],
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('despesa_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id.Despesa')),
                ('despesa', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Despesa')),
                ('ano', models.IntegerField(default=0, verbose_name='Ano')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('dt_registo', models.DateField(verbose_name='Dt.Registo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TDespesas', to='gestaugi.tiposdespesas', verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Comparticipacoes',
            fields=[
                ('compart_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID.Comparticipação')),
                ('valor_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('valor_regularizado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pago')),
                ('valor_em_divida', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor em Divida')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('tipo', models.CharField(max_length=80, verbose_name='Tipo')),
                ('dt_valor', models.DateField(verbose_name='Dt.Valor')),
                ('dt_registo', models.DateField(verbose_name='Dt.Registo')),
                ('estado', models.CharField(max_length=15, verbose_name='Estado')),
                ('dt_estado', models.DateField(default=0, verbose_name='Data')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LotesComp', to='gestaugi.lotes', verbose_name='ID Lote')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SociosComp', to='gestaugi.socios', verbose_name='ID Socio')),
            ],
        ),
        migrations.CreateModel(
            name='Anuidades',
            fields=[
                ('anuidade_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id.Anuidade')),
                ('anuidade', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Anuidade')),
                ('ano', models.IntegerField(default=0, verbose_name='Ano')),
                ('dt_pagamento', models.DateField(blank=True, null=True, verbose_name='Dt.Pagamento')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SociosAnu', to='gestaugi.socios', verbose_name='ID Socio')),
            ],
        ),
    ]
