# Generated by Django 4.2.2 on 2023-06-08 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembleias',
            fields=[
                ('assembleia_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID.Assembleia')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('orgao', models.CharField(max_length=20, verbose_name='Orgão')),
                ('cpostal', models.CharField(max_length=10, verbose_name='Cod.Postal')),
                ('localidade', models.CharField(max_length=80, verbose_name='Localidade')),
                ('dt_assembleia', models.DateField(verbose_name='Dt.Assembleia')),
                ('convocados', models.IntegerField(default=0, verbose_name='Convocados')),
                ('presencas', models.IntegerField(default=0, verbose_name='Presenças')),
                ('rep_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Representação Total')),
                ('rep_socios', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Representação Sócios')),
                ('rep_assembl', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Representação Assembleia')),
            ],
        ),
        migrations.CreateModel(
            name='AugiDashboard',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id.Registo')),
                ('numero', models.IntegerField(default=0, verbose_name='Numero')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('reconversao', models.IntegerField(default=0, verbose_name='Reconversão')),
                ('area_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Área Total')),
                ('area_media', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Área Média')),
                ('augi_menor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Augi Menor')),
                ('augi_maior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Augi Maior')),
            ],
        ),
        migrations.CreateModel(
            name='CodPostais',
            fields=[
                ('codpostal', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cod.Postal')),
                ('localidade', models.CharField(max_length=50, verbose_name='Localidade')),
            ],
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('lote_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Lote')),
                ('nlote', models.IntegerField(default=0, verbose_name='NºLote')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('local', models.CharField(max_length=80)),
                ('dt_aquisicao', models.DateField(verbose_name='Dt.Aquisição')),
                ('dt_venda', models.DateField(blank=True, null=True, verbose_name='Dt.Venda')),
                ('nfogos', models.IntegerField(default=0, verbose_name='NºFogos')),
                ('frenteslote', models.IntegerField(default=0, verbose_name='Frentes Lote')),
            ],
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('param_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id.Parametro')),
                ('vtotobra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='V.Tot.Obra')),
                ('tfrenlot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='T.Frentes Lote')),
                ('tfoglot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='T.Fogos Lote')),
                ('tarealot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='T.Areas Lote')),
            ],
        ),
        migrations.CreateModel(
            name='TiposDespesas',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id.Tipo')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('socio_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nsocio', models.IntegerField(default=0, unique=True, verbose_name='NºSócio')),
                ('nome', models.CharField(max_length=80, verbose_name='Sócio')),
                ('morada', models.CharField(max_length=80)),
                ('localidade', models.CharField(max_length=80, verbose_name='Localidade')),
                ('cpostlocal', models.CharField(max_length=80, verbose_name='Local.Cod.Post')),
                ('telemovel', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('lotes', models.CharField(max_length=80, verbose_name='Lotes')),
                ('representacao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Representação')),
                ('compdivida', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Comp. Devidas')),
                ('anuidivida', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Anuid. Devidas')),
                ('dt_admissao', models.DateField(verbose_name='Dt.Admissão')),
                ('estado', models.CharField(max_length=15)),
                ('cpostal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Codpost', to='gestaugi.codpostais', verbose_name='Cod.Postal')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('pagamento_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID.Pagamento')),
                ('pagamento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pagamento')),
                ('tipo', models.CharField(max_length=80, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('dt_pagamento', models.DateField(verbose_name='Dt.Pagamento')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LotesPag', to='gestaugi.lotes', verbose_name='ID Lote')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SociosPag', to='gestaugi.socios', verbose_name='ID Socio')),
            ],
        ),
        migrations.AddField(
            model_name='lotes',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Socios', to='gestaugi.socios', verbose_name='NºSocio'),
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('despesa_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id.Despesa')),
                ('despesa', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Despesa')),
                ('ano', models.IntegerField(default=0, verbose_name='Ano')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('dt_registo', models.DateField(verbose_name='Dt.Registo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TDespesas', to='gestaugi.tiposdespesas', verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Comparticipacoes',
            fields=[
                ('compart_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID.Comparticipação')),
                ('valor_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('tipo', models.CharField(max_length=80, verbose_name='Tipo')),
                ('dt_valor', models.DateField(verbose_name='Dt.Valor')),
                ('dt_registo', models.DateField(verbose_name='Dt.Registo')),
                ('estado', models.CharField(max_length=15, verbose_name='Estado')),
                ('dt_estado', models.DateField(default=0, verbose_name='Data')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LotesComp', to='gestaugi.lotes', verbose_name='ID Lote')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SociosComp', to='gestaugi.socios', verbose_name='ID Socio')),
            ],
        ),
        migrations.CreateModel(
            name='Anuidades',
            fields=[
                ('anuidade_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id.Anuidade')),
                ('anuidade', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Anuidade')),
                ('ano', models.IntegerField(default=0, verbose_name='Ano')),
                ('dt_pagamento', models.DateField(blank=True, null=True, verbose_name='Dt.Pagamento')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SociosAnu', to='gestaugi.socios', verbose_name='ID Socio')),
            ],
        ),
        migrations.CreateModel(
            name='Presencas',
            fields=[
                ('presenca_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID.Presença')),
                ('orgao', models.CharField(max_length=20, verbose_name='Orgão')),
                ('dt_assembleia', models.DateField(verbose_name='Dt.Assembleia')),
                ('representacao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Representação')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SociosPres', to='gestaugi.socios', verbose_name='Socio')),
            ],
            options={
                'unique_together': {('socio', 'orgao', 'dt_assembleia')},
            },
        ),
    ]
