# Generated by Django 4.1.3 on 2023-03-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaugi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuidades',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SociosAnu', to='gestaugi.socios', verbose_name='ID Socio'),
        ),
        migrations.AlterField(
            model_name='comparticipacoes',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LotesComp', to='gestaugi.lotes', verbose_name='ID Lote'),
        ),
        migrations.AlterField(
            model_name='comparticipacoes',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SociosComp', to='gestaugi.socios', verbose_name='ID Socio'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TDespesas', to='gestaugi.tiposdespesas', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Socios', to='gestaugi.socios', verbose_name='NºSocio'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='socio_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
