# Generated by Django 4.1.3 on 2023-03-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaugi', '0003_pagamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparticipacoes',
            name='valor_em_divida',
        ),
        migrations.RemoveField(
            model_name='comparticipacoes',
            name='valor_regularizado',
        ),
        migrations.AlterField(
            model_name='comparticipacoes',
            name='valor_calculado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor'),
        ),
    ]
