# Generated by Django 4.1.3 on 2023-03-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaugi', '0004_remove_comparticipacoes_valor_em_divida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LotesPag', to='gestaugi.lotes', verbose_name='ID Lote'),
        ),
    ]
