# Generated by Django 4.1.3 on 2023-03-19 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaugi', '0005_pagamentos_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presencas',
            fields=[
                ('presenca_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID.Presença')),
                ('orgao', models.CharField(max_length=20, verbose_name='Orgão')),
                ('dt_assembleia', models.DateField(verbose_name='Dt.Assembleia')),
                ('representacao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Representação')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SociosPres', to='gestaugi.socios', verbose_name='ID Socio')),
            ],
        ),
    ]
