# Generated by Django 4.1.3 on 2023-03-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaugi', '0006_presencas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencas',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SociosPres', to='gestaugi.socios', verbose_name='Socio'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Sócio'),
        ),
    ]
