# Generated by Django 4.1.3 on 2023-03-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaugi', '0009_alter_assembleias_rep_socios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembleias',
            name='rep_socios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Representação Sócios'),
        ),
    ]
