# Generated by Django 4.1.3 on 2023-03-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaugi', '0010_alter_assembleias_rep_socios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='nsocio',
            field=models.IntegerField(default=0, unique=True, verbose_name='NºSócio'),
        ),
    ]
