# Generated by Django 4.1.3 on 2023-03-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaugi', '0011_alter_socios_nsocio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presencas',
            unique_together={('socio', 'orgao', 'dt_assembleia')},
        ),
    ]
