# Generated by Django 4.1.3 on 2023-03-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaugi', '0012_alter_presencas_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lotes',
            unique_together={('nlote', 'dt_venda')},
        ),
    ]
