# Generated by Django 4.1.3 on 2023-03-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaugi', '0014_alter_lotes_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('param_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id.Parametro')),
                ('vtotobra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='V.Tot.Obra')),
                ('tfrenlot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='T.Fre.Lote')),
                ('tfoglot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='T.Fog.Lote')),
                ('tarealot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='T.Areas Lote')),
            ],
        ),
    ]
